#!/bin/bash
# automatic analysis the run results in every themes, and help with the tree.py tools
# to implement the tree hierarchy demonstration. 
# Usage: tree.sh hlda-run outfile
# lengerfulluse 
# Dec 28, 2012

if [ $# -ne 2 ] ;
then
    echo "Usage: tree.sh hlda-run outdir"
    exit 1;
fi

if [ ! -d $2 ] ;
then
	echo "$2 is not a valid output directory"
	exit 1
#	echo "now , create output directory $2"
#	mkdir -p $2
fi

echo "Now analysis the $1 directory generated by hLDA"

runDir=`find $1 -name 'run*'`

for run in $runDir
do
    dir=`dirname $run`
    theme=`basename $dir`
    echo "[$theme]"
    mode=$run'/'mode
    vocab=$dir'/words.temp'
    dmap=$dir'/RemoveStop.temp'
    currun=`basename $run`
    outdotfile=$theme'_'$currun'.dot'
    outpngfile=$theme'_'$currun'.png'
    curoutdot=$dir'/'$outdotfile
    outdot=$2$outdotfile
    outpng=$2$outpngfile
    python tree.py dot $mode $vocab $dmap $curoutdot
#    echo "to convert encoding for $outdot"
#    iconv -c -f GB2312 -t UTF-8 $curoutdot > $outdot
    echo "generate png $outpng"
    dot -Tpng $curoutdot -o $outpng 

    echo "-----------------------------------------------"
done

echo "store the output result to $2 "

